### ISSUE TITLE
Modèle Joueur

### ISSUE THREAD

**Issue by mdevoldere** [Puissance4/P4_DJS#1]
Un joueur est caractérisé par les attributs suivants: **username**, **password**, **email**, **totalGames**, **totalScore**, **dateCreation**, **lastLogged**, **isLogged**.

Déterminer le type de chacun des attributs, modéliser et implémenter la classe "Player".

**Comment by JJeanniard** [comment]
Bonjour,
Votre ticket va t’être étudié par l'équipe et assigné à une tache.
Merci pour votre suggestion.
